version: '3.5'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=demo
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - mongodb:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - mongodb
    restart: unless-stopped

networks:
  mongodb:
    driver: bridge
    
volumes:
  mongodb:
