version: '3.5'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: demo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - mongodb
    restart: unless-stopped

networks:
  mongodb:
    driver: bridge
    
volumes:
  mongodb:
